<?php

use Phinx\Migration\AbstractMigration;

class SeedUsersTable extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function up()
    {
        $password_hash = password_hash('verysecret', PASSWORD_DEFAULT);
        $this->execute("
        insert into users (first_name, last_name, email, password)
        values
        ('Cosmin', 'Burdalescu', 'cosmin@burdalescu.com', '$password_hash')
        ");
    }

    public function down()
    {
        parent::down(); // TODO: Change the autogenerated stub
    }
}
